import express from "express";
import userRouter from "./modules/users/users.routes.js";
import carsRouter from "./modules/cars/cars.routes.js";
import rentalRouter from "./modules/rental/rental.routes.js";
const app = express();
const port = 3000;
app.use(express.json());
app.use("/users", userRouter);
app.use("/cars", carsRouter);
app.use("/rentals", rentalRouter);
app.get("/", (req, res) => res.send("Hello World!"));
app.listen(port, () => console.log(`Example app listening on port ${port}!`));
